services:
  nginx:
    image: nginx:latest
    ports:
      - "8919:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cdn-content:/cdn-content
      - ./upload-ui:/upload-ui
    depends_on:
      - upload

  upload:
    image: python:3.14.0a7-alpine
    hostname: upload
    volumes:
      - ./cdn-content:/cdn-content
      - ./upload-server:/app
    working_dir: /app
    command: ash -c "pip install flask && python app.py"
